listen=YES
listen_ipv6=NO
background=NO
seccomp_sandbox=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

local_root=/var/www/html
chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40005
pasv_address=127.0.0.1

pam_service_name=vsftpd
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log
