listen=YES # vsftpd itself will then take care of listening for and handling incoming connections.
listen_ipv6=NO # vsftpd will not listen on an IPv6 socket 
background=NO # When enabled, and vsftpd is started in "listen" mode, vsftpd will background the listener process
seccomp_sandbox=NO 

anonymous_enable=NO # Controls whether anonymous logins are permitted or not.
local_enable=YES # Controls whether local logins are permitted or not
write_enable=YES # This controls whether any FTP commands which change the filesystem are allowed or not. 
local_umask=022 # The value that the umask (file permission) for file creation is set to for local user

local_root=/var/www/html # This option represents a directory which vsftpd will try to change into after a local
chroot_local_user=YES # all users of VSFTPD/FTP will be limited to accessing only files in their own home directory. 
allow_writeable_chroot=YES

pasv_enable=YES # "Passive File Transfer Protocol," a mode where the FTP client requests the server to provide a port for data transfer, allowing the client to initiate the connection.
pasv_min_port=40000 # The minimum port to allocate for PASV style data connections.
pasv_max_port=40005 # The maximum port to allocate for PASV style data connections.
pasv_address=127.0.0.1 # override the IP address that vsftpd will advertise in response to the PASV command.

pam_service_name=vsftpd # This string is the name of the PAM service vsftpd will use.
userlist_enable=YES # vsftpd will load a list of usernames, from the filename given by userlist_file.
userlist_file=/etc/vsftpd.userlist # the name of the file loaded when the userlist_enable option is active.
userlist_deny=NO # users will be denied login unless they are explicitly listed in the file specified by userlist_file.

xferlog_enable=YES # log file will be maintained detailling uploads and downloads.
xferlog_file=/var/log/vsftpd.log # the name of the file to which we write the wu-ftpd style transfer log.
